dist: trusty
sudo: required
cache:
  directories:
      - $HOME/.m2
      - $HOME/.ccache
      - $HOME/downloads
  timeout: 1000
addons:
  apt:
    packages:
    - yasm
    - nasm

language: java
services:
      - docker

matrix:
jobs:
   include:
      - os: osx
        osx_image: xcode8.3
        env: PROJ=tensorflow OS=macosx-x86_64
        install: true
        script: ./ci/install-travis.sh
      - os: osx
        osx_image: xcode8.3
        env: PROJ=tensorflow OS=macosx-x86_64 EXT=-gpu
        install: true
        script: ./ci/install-travis.sh
